#Spigot & Paper (-forks) related
name: HopeCommander-Spigot
main: me.hopedev.hopecommander.spigot.SpigotMain
version: 2.0.1
folia-supported: true
description: A Bridge between spigot, bungee and velocity, one way only
author: HopeDev, Larrox
commands:
  hopecommander:
    description: Main Command for HopeCommander
    permission: hc.command